import { Book } from "./api/api";

export const dummy_book: Book[] = [
    {
      date: "2025-02-06",
      time: "12:30",
      bookTitle: "책 제목 1",
      bookimage: "../../image_data/test1.png",
      question: "이 책은 무엇을 다루고 있을까?",
    },
    {
      date: "2025-02-06",
      time: "14:00",
      bookTitle: "책 제목 2",
      bookimage: "../../image_data/test2.png",
      question: "이야기의 결말은 어떻게 될까?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 3",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 4",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 5",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 6",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 7",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 8",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 9",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 10",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 11",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 12",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
    {
      date: "2025-02-06",
      time: "16:45",
      bookTitle: "책 제목 13",
      bookimage: "../../image_data/test3.jpg",
      question: "주인공이 맞닥뜨릴 가장 큰 도전은?",
    },
  ];